name: Latest blog post workflow
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dohun.kim/rss"
          template: "<sup>[$title]($url)</sup><br/>"
          max_post_count: 6